name: Generate Deployment Files

on:
  push:
    branches:
      - main

jobs:
  generate-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install -r requirements.txt
      working-directory: .  # Update this path

    - name: Run Python Script
      run: python main.py
      working-directory: .  # Update this path
